=== gnominomnom/Technoweb1/TW2/html/bibliographie.dtd
<?xml version="1.0" encoding="UTF-8"?>
  <!ELEMENT bibliographie (publication+)>
  <!ELEMENT publication (titre,auteurs+,pages+,annee)>
  <!ATTLIST publication type ( ARTICLE | CONFERENCE ) #REQUIRED>
  <!ELEMENT titre (#PCDATA)>
  <!ELEMENT auteurs (auteur+)>
  <!ELEMENT auteur (#PCDATA)>
  <!ELEMENT pages (#PCDATA)>
  <!ELEMENT annee (#PCDATA)>

=== gnominomnom/Technoweb1/TW2/html/bibliographie.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE bibliographie SYSTEM "bibliographie.dtd">
<?xml-stylesheet type="text/css" href="bibliographie.css" ?> 
<bibliographie>
  <publication type="CONFERENCE">
    <titre>Noémie and Bianca are awesome</titre>
    <auteurs>
      <auteur>Bianca</auteur>
      <auteur>Noémie</auteur>
    </auteurs>
    <pages>500</pages>
    <annee>2019</annee>
  </publication>

  <publication type="ARTICLE">
    <titre>Noémie and Bianca are still awesome</titre>
    <auteurs>
      <auteur>Malandain</auteur>
      <auteur>Delestre</auteur>
    </auteurs>
    <pages>600</pages>
    <annee>2019</annee>
  </publication>
</bibliographie>
