=== gnominomnom/Technoweb1/TW2/html/cd.dtd
<?xml version="1.0" encoding="utf-8" ?>
  <!ELEMENT cd ((interprete+),titre, groupe, edition, critiques)>
  <!ELEMENT interprete (nom, prenom)>
  <!ELEMENT nom (#PCDATA)>
  <!ELEMENT prenom (#PCDATA)>
  <!ELEMENT titre (#PCDATA)>
  <!ELEMENT groupe (#PCDATA)>
  <!ELEMENT edition (nom, lieu, pays, annee, (admin?))>
  <!ELEMENT lieu (#PCDATA)>
  <!ELEMENT pays (#PCDATA)>
  <!ELEMENT annee (#PCDATA)>
  <!ELEMENT admin (plages, (isbn?), prix)>
  <!ELEMENT plages (#PCDATA)>
  <!ELEMENT prix (#PCDATA | EMPTY)*>
  <!ATTLIST prix monnaie CDATA #IMPLIED ><!--#REQUIRED-->
  <!ELEMENT critiques (resume, remarque)>
  <!ELEMENT resume ((para+))>
  <!ELEMENT para (#PCDATA)>
  <!ELEMENT remarque (#PCDATA)>
<!--PCDATA=parsed character data-->

=== gnominomnom/Technoweb1/TW2/TW2/TDM02-Annexes/cdA.xml
<?xml version="1.0" encoding="utf-8" standalone='no'?>

<!DOCTYPE interpretes SYSTEM "cd.dtd">
<cd>
  <interprete>
    <nom>Michard</nom>
    <prenom>Alain</prenom>
  </interprete>

  <titre>Vive la vie !</titre>

  <edition>
    <nom>Epigramme</nom>
    <lieu>Paris</lieu>
    <pays>France</pays>
    <annee>2001</annee>
  </edition>

  <admin>
    <plages>10</plages>
    <isbn> type="hardback">ISBN 2-212-09206-7</isbn>
    <prix monnaie="EUR">???</prix>
  </admin>

  <critiques>
    <resume>
      <para>Faux hardrock.</para>
      <para>CD remasteris√©.</para>
    </resume>
    <remarque>Plus sur le site des editions Epigramme : http://www.editions-epigramme/cd/michard.
    </remarque>
  </critiques>

</cd>

=== gnominomnom/Technoweb1/TW2/TW2/TDM02-Annexes/cdB.xml
<?xml version="1.0" encoding="utf-8" ?>

<!DOCTYPE cd SYSTEM "cd.dtd">

<cd>
  <interprete>
    <nom>Guillot</nom>
    <prenom>Agnès</prenom>
  </interprete>

  <interprete>
    <nom>Daucé</nom>
    <prenom>Emmanuel</prenom>
  </interprete>

  <titre>Rock en stock !</titre>

  <groupe>Au fond de l'eau</groupe>

  <edition>
    <nom>SoundSystem</nom>
    <lieu>Paris</lieu>
    <pays>France</pays>
    <annee>2002</annee>
    <admin>
      <plages>316</plages>
      <prix monnaie="EUR">80.00</prix>
    </admin>
  </edition>

  <critiques>
    <resume>
      <para>Blabla.</para>
    </resume>
    <remarque>Voir aussi le site Hermès: http://www.soundsystem.fr/fr/.</remarque>
  </critiques>
</cd>
